"""
Auth Router — user registration and profile retrieval.

Uses device_id (UUID generated by the mobile app) as the primary identifier.
No passwords needed for this local MVP.
"""

import uuid
from datetime import datetime, timezone
from fastapi import APIRouter, HTTPException
from api.schemas import RegisterRequest, UserResponse
from api.database import get_db

router = APIRouter(prefix="/auth", tags=["Auth"])


@router.post("/register", response_model=UserResponse)
async def register(body: RegisterRequest):
    """
    Register a new user or return existing user for the same device_id.
    Idempotent — calling twice with the same device_id returns the same user.
    """
    db = get_db()
    existing = await db["users"].find_one({"device_id": body.device_id})
    if existing:
        return UserResponse(
            user_id=existing["user_id"],
            device_id=existing["device_id"],
            name=existing["name"],
            created_at=existing["created_at"],
        )

    user_id = str(uuid.uuid4())
    now = datetime.now(timezone.utc)
    doc = {
        "user_id": user_id,
        "device_id": body.device_id,
        "name": body.name,
        "created_at": now,
    }
    await db["users"].insert_one(doc)
    return UserResponse(user_id=user_id, device_id=body.device_id, name=body.name, created_at=now)


@router.get("/profile/{user_id}", response_model=UserResponse)
async def get_profile(user_id: str):
    """Fetch a user profile by user_id."""
    db = get_db()
    user = await db["users"].find_one({"user_id": user_id})
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    return UserResponse(
        user_id=user["user_id"],
        device_id=user["device_id"],
        name=user["name"],
        created_at=user["created_at"],
    )
